Backups: true
NoRegCombat: true
NoNetherPortals: true
AdminState: true
SignColors: true
Loginz: true
AdminChat: true
AntiPvPLog: true
BPermsSimplified: true
Invis: true
HeroExpBoost: true
LevelUp: true